apiVersion: v1

data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::467107197573:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1L2QSH7VQCOQI
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::467107197573:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-16T13:00:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3934"
  uid: 8e36e9b3-ee02-4657-9d47-bbd9b802b39a
